times = ('Botafogo', 'Palmeiras', 'Fluminense', 'Atlético-MG', 'Cruzeiro', 'Flamengo', 'Athletico-PR', 'São Paulo', 'Santos', 'Grêmio', 'Fortaleza', 'Bragantino', 'Bahia', 'Cuiabá', 'Internacional', 'Goiás', 'Vasco da Gama', 'Corinthians', 'América-MG', 'Coritiba')
print("-=-=-=-=-="*8)
print(f"Lista de times do Brasileirão: {times}")
print("-=-=-=-=-="*8)
print(f"Os 5 primeiros colocados são: {times[0:5]}")
print("-=-=-=-=-="*8)
print(f"Os 4 últimos colocados são: {times[15:19]}")
print("-=-=-=-=-="*8)
print(f"Os 4 últimos colocados são: {times[15:19]}")
print("-=-=-=-=-="*8)
print(f"Times em ordem alfabética: {sorted(times)}")
print("-=-=-=-=-="*8)
print(f"O são paulo está na {times.index('São Paulo')+1}ª posição")
